#script para crear un rig de camara
import maya.cmds as cmds

cmds.camera(name="Rigged_Cam",)
cmds.setAttr("Rigged_Cam1.template", 1)
cmds.circle(name="Cam_Aim_CTR",normal=(0,0,0), radius=.3)
cmds.setAttr("Cam_Aim_CTR.rotateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.rotateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.rotateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Aim_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.addAttr(longName="Follow",keyable=True,attributeType="enum",enumName="Cam_CTR:World:")
cmds.group(name="Cam_Aim_AUX")
cmds.group(name="Cam_Aim_OFF")
cmds.setAttr("Cam_Aim_OFF.translateZ",  -5)
cmds.spaceLocator(name="Camera_Up")
cmds.group(name="Camera_Up_Aux")
cmds.group(name="Camera_Up_OFF")
cmds.setAttr("Camera_Up_OFF.translateY", 2)
cmds.setAttr("Camera_Up_OFF.visibility", 0)
cmds.select("Cam_Aim_CTR","Rigged_Cam1")
cmds.aimConstraint(maintainOffset=True,weight=1,aimVector=(1,0,0),upVector=(0,1,0),worldUpType="object",worldUpObject="Camera_Up")
cmds.select("Cam_Aim_OFF","Rigged_Cam1","Camera_Up_OFF")
cmds.group(name="Rigged_Cam_AUX")
cmds.group(name="Rigged_Cam_OFF")

cmds.circle(name="Cam_Shake_CTR",normal=(0,0,0),radius=1)
cmds.setAttr("Cam_Shake_CTR.translateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.translateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.translateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.rotateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.rotateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.rotateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_Shake_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.group(name="Cam_Shake_AUX")
cmds.group(name="Cam_Shake_OFF")
cmds.setAttr("Cam_Shake_OFF.translateZ", 3)

cmds.ambientLight(name="keyLight")
cmds.setAttr("keyLight.visibility", 0)
cmds.ambientLight(name="FillLight")
cmds.setAttr("FillLight.visibility", 0)
cmds.ambientLight(name="BounceLight")
cmds.setAttr("BounceLight.visibility", 0)
cmds.circle(name="keyLight_CTR",normal=(0,1,0),radius=1)
cmds.setAttr("keyLight_CTR.rotateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.rotateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.rotateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("keyLight_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.addAttr(longName="Intensity",keyable=True,defaultValue=1,)
cmds.circle(name="FillLight_CTR",normal=(0,1,0),radius=1)
cmds.setAttr("FillLight_CTR.rotateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.rotateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.rotateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("FillLight_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.addAttr(longName="Intensity",keyable=True,defaultValue=.3,)
cmds.circle(name="BounceLight_CTR",normal=(0,1,0),radius=1)
cmds.setAttr("BounceLight_CTR.rotateX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.rotateY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.rotateZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("BounceLight_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.addAttr(longName="Intensity",keyable=True,defaultValue=.3,)

lights=cmds.ls("keyLight_CTR","FillLight_CTR","BounceLight_CTR")

for light in lights:
    lAuxGrp= cmds.group(empty=True)
    cmds.parent(light, lAuxGrp)
    lAuxName=light.replace("CTR","AUX")
    cmds.rename(lAuxGrp, lAuxName)
    lOffGrp= cmds.group(empty=True)
    cmds.parent(lAuxName,lOffGrp)
    cmds.rename(lAuxGrp, lAuxName.replace("AUX","OFF"))
    
cmds.parent("keyLight","keyLight_CTR")
cmds.parent("FillLight","FillLight_CTR")
cmds.parent("BounceLight","BounceLight_CTR")

cmds.setAttr("keyLight_OFF.translateX", 6)
cmds.setAttr("keyLight_OFF.translateY", 3)
cmds.setAttr("FillLight_OFF.translateX", -7)
cmds.setAttr("FillLight_OFF.translateY", 3)
cmds.setAttr("BounceLight_OFF.translateZ",-2)
cmds.setAttr("BounceLight_OFF.translateY", -1)

cmds.select("keyLight_OFF","FillLight_OFF","BounceLight_OFF")
cmds.group(name="LightSet")

cmds.polyPlane(name="cinema3rds",subdivisionsX=3,subdivisionsY=3,axis=(0,0,1))
cmds.setAttr("cinema3rds.translateZ", -1.991)
cmds.setAttr("cinema3rds.translateY", .001)
cmds.setAttr("cinema3rds.scaleX", 2.05)
cmds.setAttr("cinema3rds.scaleY", 1.16)
cmds.setAttr("cinema3rdsShape.template", 1)

cmds.polyPlane(name="safeTitle",subdivisionsX=1,subdivisionsY=1,axis=(0,0,1))
cmds.setAttr("safeTitle.translateZ", -1.991)
cmds.setAttr("safeTitle.scaleX", 1.65)
cmds.setAttr("safeTitle.scaleY", .93)
cmds.setAttr("safeTitleShape.template", 1)

cmds.polyPlane(name="title3rds",subdivisionsX=3,subdivisionsY=3,axis=(0,0,1))
cmds.setAttr("title3rds.translateZ", -1.991)
cmds.setAttr("title3rds.scaleX", 1.65)
cmds.setAttr("title3rds.scaleY", .93)
cmds.setAttr("title3rdsShape.template", 1)

cmds.select("cinema3rds","safeTitle","title3rds")

cmds.group(name="Cam_Grids")
    
cmds.circle(name="offsetRoot_CTR",normal=(0,1,0),radius=3)
cmds.setAttr("offsetRoot_CTR.overrideEnabled", 1)
cmds.circle(name="Root_CTR",normal=(0,1,0),radius=2.5)
cmds.setAttr("Root_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Root_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Root_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Root_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Root_CTR.overrideEnabled", 1)

cmds.circle(name="Main_CTR",normal=(0,1,0),radius=2)
cmds.setAttr("Main_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Main_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Main_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Main_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Main_CTR.overrideEnabled", 1)

cmds.circle(name="TRS_CTR",normal=(0,1,0),radius=1.5)
cmds.setAttr("TRS_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("TRS_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("TRS_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("TRS_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.setAttr("TRS_CTR.overrideEnabled", 1)

cmds.circle(name="Cam_CTR",normal=(0,1,0),radius=1)
cmds.setAttr("Cam_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.setAttr("Cam_CTR.overrideEnabled", 1)

cmds.circle(name="CP_CTR",normal=(0,1,0),radius=.5)
cmds.setAttr("CP_CTR.scaleX",lock=True,keyable=False,channelBox=False)
cmds.setAttr("CP_CTR.scaleY",lock=True,keyable=False,channelBox=False)
cmds.setAttr("CP_CTR.scaleZ",lock=True,keyable=False,channelBox=False)
cmds.setAttr("CP_CTR.visibility",lock=True,keyable=False,channelBox=False)
cmds.setAttr("CP_CTR.overrideEnabled", 1)

items=cmds.ls("offsetRoot_CTR","Root_CTR","Main_CTR","TRS_CTR","Cam_CTR","CP_CTR")

for item in items:
        auxGrp = cmds.group(empty=True)
        cmds.parent(item, auxGrp)
        auxName = item.replace("CTR","AUX")
        cmds.rename(auxGrp, auxName )
        offGrp = cmds.group(empty=True)
        cmds.parent(auxName, offGrp)
        cmds.rename(auxGrp, auxName.replace("AUX","OFF"))

cmds.parent("Cam_Grids","CP_CTR")
cmds.parent("Rigged_Cam_OFF","CP_CTR") 
cmds.parent("Cam_Shake_OFF","CP_CTR")
cmds.parent("LightSet","CP_CTR")     
cmds.parent("CP_OFF","Cam_CTR")
cmds.parent("Cam_OFF","TRS_CTR")
cmds.parent("TRS_OFF","Main_CTR")
cmds.parent("Main_OFF","Root_CTR")
cmds.parent("Root_OFF","offsetRoot_CTR")

cmds.select("Root_CTR")
cmds.addAttr(longName="Lens_Mm",keyable=True,defaultValue=35)
cmds.addAttr(longName="Near_Clip",keyable=True,defaultValue=0.1)
cmds.addAttr(longName="Far_Clip",keyable=True,defaultValue=1000000)
cmds.addAttr(longName="Displayables",keyable=True,attributeType="enum",enumName="___")
cmds.addAttr(longName="CP_Vis",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.CP_Vis",keyable=False,channelBox=True)
cmds.addAttr(longName="Disp_Aim",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Disp_Aim",keyable=False,channelBox=True)
cmds.addAttr(longName="Disp_Frustum",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Disp_Frustum",keyable=False,channelBox=True)
cmds.addAttr(longName="Cinematic_3rds",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Cinematic_3rds",keyable=False,channelBox=True)
cmds.addAttr(longName="Safe_3rds",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Safe_3rds",keyable=False,channelBox=True)
cmds.addAttr(longName="Safe_Title",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Safe_Title",keyable=False,channelBox=True)
cmds.addAttr(longName="Shake_Vis",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Shake_Vis",keyable=False,channelBox=True)
cmds.addAttr(longName="Light_Set",keyable=True,attributeType="bool")
cmds.setAttr("Root_CTR.Light_Set",keyable=False,channelBox=True)

cmds.connectAttr("Root_CTR.CP_Vis","CP_CTRShape.lodVisibility")
cmds.connectAttr("Root_CTR.Disp_Aim","Cam_Aim_AUX.visibility")
cmds.connectAttr("Root_CTR.Disp_Frustum","Rigged_CamShape2.displayCameraFrustum")
cmds.connectAttr("Root_CTR.Cinematic_3rds","cinema3rds.visibility")
cmds.connectAttr("Root_CTR.Safe_3rds","title3rds.visibility")
cmds.connectAttr("Root_CTR.Safe_Title","safeTitle.visibility")
cmds.connectAttr("Root_CTR.Shake_Vis","Cam_Shake_AUX.visibility")
cmds.connectAttr("Root_CTR.Light_Set","LightSet.visibility")
cmds.connectAttr("keyLight_CTR.Intensity","keyLightShape.intensity")
cmds.connectAttr("BounceLight_CTR.Intensity","BounceLightShape.intensity")
cmds.connectAttr("FillLight_CTR.Intensity","FillLightShape.intensity")
cmds.connectAttr("Root_CTR.Lens_Mm","Rigged_CamShape2.focalLength")
cmds.connectAttr("Root_CTR.Near_Clip","Rigged_CamShape2.nearClipPlane")
cmds.connectAttr("Root_CTR.Far_Clip","Rigged_CamShape2.farClipPlane")

cmds.shadingNode("multiplyDivide",asUtility=True,name="GridsDiv")
cmds.setAttr("GridsDiv.operation", 2)
cmds.setAttr("GridsDiv.input1.input1X", 35)
cmds.setAttr("GridsDiv.input1.input1Y", 35)
cmds.connectAttr("Rigged_CamShape2.focalLength","GridsDiv.input2.input2X")
cmds.connectAttr("Rigged_CamShape2.focalLength","GridsDiv.input2.input2Y")
cmds.connectAttr("GridsDiv.output.outputX","Cam_Grids.scaleX")
cmds.connectAttr("GridsDiv.output.outputY","Cam_Grids.scaleY")


